clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "



while :
do

  python3 /home/ubuntu/Desktop/admatvcryptonite/BTC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ETH.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/USDT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BNB.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XRP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BUSD.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ADA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DOGE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MATIC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SOL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DOT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SHIB.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LTC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TRX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AVAX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/UNI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WBTC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ATOM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LINK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ETC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XMR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BCH.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/APT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LDO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XLM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/HBAR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FIL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/NEAR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/APE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ALGO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/VET.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/QNT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ICP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GRT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FTM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MANA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AAVE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/EOS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/EGLD.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AXS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FLOW.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/THETA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SAND.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XTZ.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LUNC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/IMX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MINA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CHZ.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RPL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CRV.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FXS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DASH.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ZEC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MKR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BTTC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CAKE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/KLAY.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XEC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GMX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/IOTA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SNX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/NEO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TWT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RUNE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LRC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FTT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AGIX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PAXG.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OSMO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ZIL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BNX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CVX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ROSE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ROSE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RNDR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ENJ.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BAT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/STX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DYDX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/1INCH.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LUNA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/NEXO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ASTR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CELO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/HOT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/KAVA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MAGIC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/COMP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RVN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FET.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WOO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/HNT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DCR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XEM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/T.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TFUEL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SSV.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BAL.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatvcryptonite/BAL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ONE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GALA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/JASMY.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SUSHI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ENS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/USTC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OCEAN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/KSM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/IOTX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ANKR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/QTUM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GMT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AUDIO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/INJWAVES.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/YFI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MASK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GLMR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LPT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GLM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/JST.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/KDA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BAND.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FLUX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OMG.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SKL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ICX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ZRX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/HIVE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AMP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ONT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/IOST.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RSR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SFP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SXP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ZEN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ILV.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WAXP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BICO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RLC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CFX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/STORJ.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SYS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DGB.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CKB.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CELR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/VGX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PEOPLE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/STG.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LSK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/UMA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/HOOK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CHR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/KNC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SCRT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ELF.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/HFT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SLP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PLA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/API3.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PUNDIX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MOB.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/NMR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GAL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XNO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ANT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GTC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SNT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GFT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CVC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/COTI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/POLYX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CTSI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PYR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DUSK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/REQ.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DEXE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ONG.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/STEEM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/HIGH.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ARDR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ALPHA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DENT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RAD.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PHA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/POWR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SRM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MBOX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PROM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SPELL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/IQ.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/REN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MDX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WIN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ACH.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XVS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/NKN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/STRAX.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatvcryptonite/STRAX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XRPUP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XRPDOWN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MULTI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LINKUP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LINKDOWN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/HIFI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GBP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/EUR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ETHUP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ETHDOWN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BTCUP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BTCDOWN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BNBUP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BNBDOWN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BETH.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AUD.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ADAP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ADADOWN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/JUV.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OG.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PERL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ATM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/UFT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CVP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PNT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ACM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MIR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TORN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OAX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WABI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AKRO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FOR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PROS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ANC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DREP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AST.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/VIB.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DF.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WTC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OOKI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DOCK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AION.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FIDA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/KEY.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FRONT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/EPX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AMB.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CREAM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/VITE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PORTO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BURGER.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AUTO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/HARD.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WING.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FARM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PSG.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ADX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TROY.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/COS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CITY.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SANTOS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/QLS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/POLS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ALPACA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PHB.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SNM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TRU.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PERP.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WAN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LTO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DEGO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AUCTION.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BOND.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BIFI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/KMD.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ALPINE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TOMO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ALCX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/IDEX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DIA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/REI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LEVER.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FIS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LINA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MDT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AGLD.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/QI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/VIDT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AVA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ERN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BTS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/KP3R.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CLV.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CHESS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ORN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BLZ.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/VOXEL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/PIVX.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatvcryptonite/PIVX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GAS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FIRO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/NEBL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BAR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DATA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/QUICK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LAZIO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BEL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/UNFI.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/IRIS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/NULS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TRB.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FIO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/POND.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/JOE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/VTHO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ACA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BSW.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FUN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ALICE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TLM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CTK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WRX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OGN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/REEF.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BNT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DAR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/QKC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MTL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/OXT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/STMX.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/DODO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BETA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ATA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/C98.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ARK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FORTH.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RIF.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/YGG.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LOOM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/UTK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/AERGO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MBL.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SUN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BADGER.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/SUPER.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MOVR.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/CTXC.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RARE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TKO.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/RAY.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/XVG.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LIT.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/COCOS.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/WNXM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/ARPA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/GHST.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/MLN.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/BAKE.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/YFII.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/TVK.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/FLM.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/LOKA.py &
  python3 /home/ubuntu/Desktop/admatvcryptonite/%launcher%

clear
done
